on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ["22.3", "23.3", "24.2"]
        rebar3: ["3.18.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 xref
      - run: rebar3 dialyzer
      - run: rebar3 eunit
      - run: rebar3 ct
